<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>bb7c8903-36ca-427b-bfd3-1f40835bbd57</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\Common\Interfaces\" />
    <Folder Include="Data\" />
    <Folder Include="Domain\Base\" />
    <Folder Include="Domain\Configurations\" />
    <Folder Include="Infrastructure\Service\" />
    <Folder Include="Presentation\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.20.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
  </ItemGroup>

</Project>
